### ISSUE TITLE
Pre element fix broke unit test

### ISSUE THREAD

**Issue by Teun** [SimpleBrowserDotNet/SimpleBrowser#159]
TeamCity reports:

SimpleBrowser.UnitTests.dll: SimpleBrowser.UnitTests.OfflineTests (1)
Parsing.PreElement 	

Test(s) failed.   Expected: True
  But was:  False

   at NUnit.Framework.Assert.That(Object actual, IResolveConstraint expression, String message, Object[] args)
   at NUnit.Framework.Assert.IsTrue(Boolean condition)
   at SimpleBrowser.UnitTests.OfflineTests.Parsing.PreElement() in z:\Builds\work\da0a63b84f7a1b55\SimpleBrowser.UnitTests\OfflineTests\Parsing.cs:line 28

**Comment by kevingy** [comment]
It passes locally. I bet there is some CRLF conversion happening somewhere - probably in Elements.htm - after the files are checked in. I'll look into it.

**Comment by kevingy** [comment]
Fixed
